using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ADSDataDirect.Core.Static
{
    public class DmaLookup
    {
        public static List<DMA> US
        {
            get
            {
                return all.Where(x => x.country == "US").ToList();
            }

            set
            {
                all = value;
            }
        }

        public static List<DMA> All
        {
            get { return all; }
            set
            {
                all = value;
            }
        }

        private static List<DMA> all = new List<DMA>()
        {
             new DMA { code="100" , country="GB" , area="Anglia East" },
             new DMA { code="101" , country="GB" , area="Anglia West" },
             new DMA { code="102" , country="GB" , area="Border England" },
             new DMA { code="103" , country="GB" , area="Border Scotland" },
             new DMA { code="104" , country="GB" , area="Carlton/LWT" },
             new DMA { code="105" , country="GB" , area="Central East" },
             new DMA { code="106" , country="GB" , area="Central West" },
             new DMA { code="107" , country="GB" , area="Grampian" },
             new DMA { code="108" , country="GB" , area="Granada" },
             new DMA { code="109" , country="GB" , area="HTV Wales" },
             new DMA { code="110" , country="GB" , area="HTV West" },
             new DMA { code="111" , country="GB" , area="Meridian Maidstone" },
             new DMA { code="112" , country="GB" , area="Meridian Southampton" },
             new DMA { code="113" , country="GB" , area="STV" },
             new DMA { code="114" , country="GB" , area="Thames Valley (Central South)" },
             new DMA { code="115" , country="GB" , area="Thames Valley (Meridian Newbury)" },
             new DMA { code="116" , country="GB" , area="TTTV Tees" },
             new DMA { code="117" , country="GB" , area="TTTV Tyne" },
             new DMA { code="118" , country="GB" , area="UTV" },
             new DMA { code="119" , country="GB" , area="West Country" },
             new DMA { code="120" , country="GB" , area="YTV Lincolnshire" },
             new DMA { code="121" , country="GB" , area="YTV Sheffield" },
             new DMA { code="122" , country="GB" , area="YTV Yorkshire" },
             new DMA { code="500" , country="US" , area="Portland-Auburn, ME" },
             new DMA { code="501" , country="US" , area="New York, NY" },
             new DMA { code="502" , country="US" , area="Binghamton, NY" },
             new DMA { code="503" , country="US" , area="Macon, GA" },
             new DMA { code="504" , country="US" , area="Philadelphia, PA" },
             new DMA { code="505" , country="US" , area="Detroit, MI" },
             new DMA { code="506" , country="US" , area="Boston, MA-Manchester, NH" },
             new DMA { code="507" , country="US" , area="Savannah, GA" },
             new DMA { code="508" , country="US" , area="Pittsburgh, PA" },
             new DMA { code="509" , country="US" , area="Ft. Wayne, IN" },
             new DMA { code="510" , country="US" , area="Cleveland-Akron (Canton), OH" },
             new DMA { code="511" , country="US" , area="Washington, DC (Hagerstown, MD)" },
             new DMA { code="512" , country="US" , area="Baltimore, MD" },
             new DMA { code="513" , country="US" , area="Flint-Saginaw-Bay City, MI" },
             new DMA { code="514" , country="US" , area="Buffalo, NY" },
             new DMA { code="515" , country="US" , area="Cincinnati, OH" },
             new DMA { code="516" , country="US" , area="Erie, PA" },
             new DMA { code="517" , country="US" , area="Charlotte, NC" },
             new DMA { code="518" , country="US" , area="Greensboro-High Point-Winston Salem, NC" },
             new DMA { code="519" , country="US" , area="Charleston, SC" },
             new DMA { code="520" , country="US" , area="Augusta, GA" },
             new DMA { code="521" , country="US" , area="Providence, RI-New Bedford, MA" },
             new DMA { code="522" , country="US" , area="Columbus, GA" },
             new DMA { code="523" , country="US" , area="Burlington, VT-Plattsburgh, NY" },
             new DMA { code="524" , country="US" , area="Atlanta, GA" },
             new DMA { code="525" , country="US" , area="Albany, GA" },
             new DMA { code="526" , country="US" , area="Utica, NY" },
             new DMA { code="527" , country="US" , area="Indianapolis, IN" },
             new DMA { code="528" , country="US" , area="Miami-Ft. Lauderdale, FL" },
             new DMA { code="529" , country="US" , area="Louisville, KY" },
             new DMA { code="530" , country="US" , area="Tallahassee, FL-Thomasville, GA" },
             new DMA { code="531" , country="US" , area="Tri-Cities, TN-VA" },
             new DMA { code="532" , country="US" , area="Albany-Schenectady-Troy, NY" },
             new DMA { code="533" , country="US" , area="Hartford & New Haven, CT" },
             new DMA { code="534" , country="US" , area="Orlando-Daytona Beach-Melbourne, FL" },
             new DMA { code="535" , country="US" , area="Columbus, OH" },
             new DMA { code="536" , country="US" , area="Youngstown, OH" },
             new DMA { code="537" , country="US" , area="Bangor, ME" },
             new DMA { code="538" , country="US" , area="Rochester, NY" },
             new DMA { code="539" , country="US" , area="Tampa-St. Petersburg (Sarasota), FL" },
             new DMA { code="540" , country="US" , area="Traverse City-Cadillac, MI" },
             new DMA { code="541" , country="US" , area="Lexington, KY" },
             new DMA { code="542" , country="US" , area="Dayton, OH" },
             new DMA { code="543" , country="US" , area="Springfield-Holyoke, MA" },
             new DMA { code="544" , country="US" , area="Norfolk-Portsmouth-Newport News, VA" },
             new DMA { code="545" , country="US" , area="Greenville-New Bern-Washington, NC" },
             new DMA { code="546" , country="US" , area="Columbia, SC" },
             new DMA { code="547" , country="US" , area="Toledo, OH" },
             new DMA { code="548" , country="US" , area="West Palm Beach-Ft. Pierce, FL" },
             new DMA { code="549" , country="US" , area="Watertown, NY" },
             new DMA { code="550" , country="US" , area="Wilmington, NC" },
             new DMA { code="551" , country="US" , area="Lansing, MI" },
             new DMA { code="552" , country="US" , area="Presque Isle, ME" },
             new DMA { code="553" , country="US" , area="Marquette, MI" },
             new DMA { code="554" , country="US" , area="Wheeling, WV-Steubenville, OH" },
             new DMA { code="555" , country="US" , area="Syracuse, NY" },
             new DMA { code="556" , country="US" , area="Richmond-Petersburg, VA" },
             new DMA { code="557" , country="US" , area="Knoxville, TN" },
             new DMA { code="558" , country="US" , area="Lima, OH" },
             new DMA { code="559" , country="US" , area="Bluefield-Beckley-Oak Hill, WV" },
             new DMA { code="560" , country="US" , area="Raleigh-Durham (Fayetteville), NC" },
             new DMA { code="561" , country="US" , area="Jacksonville, FL" },
             new DMA { code="563" , country="US" , area="Grand Rapids-Kalamazoo-Battle Creek, MI" },
             new DMA { code="564" , country="US" , area="Charleston-Huntington, WV" },
             new DMA { code="565" , country="US" , area="Elmira, NY" },
             new DMA { code="566" , country="US" , area="Harrisburg-Lancaster-Lebanon-York, PA" },
             new DMA { code="567" , country="US" , area="Greenville-Spartanburg, SC-Asheville, NC-Anderson, SC" },
             new DMA { code="569" , country="US" , area="Harrisonburg, VA" },
             new DMA { code="570" , country="US" , area="Florence-Myrtle Beach, SC" },
             new DMA { code="571" , country="US" , area="Ft. Myers-Naples, FL" },
             new DMA { code="573" , country="US" , area="Roanoke-Lynchburg, VA" },
             new DMA { code="574" , country="US" , area="Johnstown-Altoona, PA" },
             new DMA { code="575" , country="US" , area="Chattanooga, TN" },
             new DMA { code="576" , country="US" , area="Salisbury, MD" },
             new DMA { code="577" , country="US" , area="Wilkes Barre-Scranton, PA" },
             new DMA { code="581" , country="US" , area="Terre Haute, IN" },
             new DMA { code="582" , country="US" , area="Lafayette, IN" },
             new DMA { code="583" , country="US" , area="Alpena, MI" },
             new DMA { code="584" , country="US" , area="Charlottesville, VA" },
             new DMA { code="588" , country="US" , area="South Bend-Elkhart, IN" },
             new DMA { code="592" , country="US" , area="Gainesville, FL" },
             new DMA { code="596" , country="US" , area="Zanesville, OH" },
             new DMA { code="597" , country="US" , area="Parkersburg, WV" },
             new DMA { code="598" , country="US" , area="Clarksburg-Weston, WV" },
             new DMA { code="600" , country="US" , area="Corpus Christi, TX" },
             new DMA { code="602" , country="US" , area="Chicago IL" },
             new DMA { code="603" , country="US" , area="Joplin, MO-Pittsburg, KS" },
             new DMA { code="604" , country="US" , area="Columbia-Jefferson City, MO" },
             new DMA { code="605" , country="US" , area="Topeka, KS" },
             new DMA { code="606" , country="US" , area="Dothan, AL" },
             new DMA { code="609" , country="US" , area="St. Louis, MO" },
             new DMA { code="610" , country="US" , area="Rockford, IL" },
             new DMA { code="611" , country="US" , area="Rochester, MN-Mason City, IA-Austin, MN" },
             new DMA { code="612" , country="US" , area="Shreveport, LA" },
             new DMA { code="613" , country="US" , area="Minneapolis-St. Paul, MN" },
             new DMA { code="616" , country="US" , area="Kansas City, MO" },
             new DMA { code="617" , country="US" , area="Milwaukee, WI" },
             new DMA { code="618" , country="US" , area="Houston, TX" },
             new DMA { code="619" , country="US" , area="Springfield, MO" },
             new DMA { code="620" , country="US" , area="Tuscaloosa, AL" },
             new DMA { code="622" , country="US" , area="New Orleans, LA" },
             new DMA { code="623" , country="US" , area="Dallas-Ft. Worth, TX" },
             new DMA { code="624" , country="US" , area="Sioux City, IA" },
             new DMA { code="625" , country="US" , area="Waco-Temple-Bryan, TX" },
             new DMA { code="626" , country="US" , area="Victoria, TX" },
             new DMA { code="627" , country="US" , area="Wichita Falls, TX & Lawton, OK" },
             new DMA { code="628" , country="US" , area="Monroe, LA-El Dorado, AR" },
             new DMA { code="630" , country="US" , area="Birmingham, AL" },
             new DMA { code="631" , country="US" , area="Ottumwa, IA-Kirksville, MO" },
             new DMA { code="632" , country="US" , area="Paducah, KY-Cape Girardeau, MO-Harrisburg-Mount Vernon, IL" },
             new DMA { code="633" , country="US" , area="Odessa-Midland, TX" },
             new DMA { code="634" , country="US" , area="Amarillo, TX" },
             new DMA { code="635" , country="US" , area="Austin, TX" },
             new DMA { code="636" , country="US" , area="Harlingen-Weslaco-Brownsville-McAllen, TX" },
             new DMA { code="637" , country="US" , area="Cedar Rapids-Waterloo-Iowa City & Dubuque, IA" },
             new DMA { code="638" , country="US" , area="St. Joseph, MO" },
             new DMA { code="639" , country="US" , area="Jackson, TN" },
             new DMA { code="640" , country="US" , area="Memphis, TN" },
             new DMA { code="641" , country="US" , area="San Antonio, TX" },
             new DMA { code="642" , country="US" , area="Lafayette, LA" },
             new DMA { code="643" , country="US" , area="Lake Charles, LA" },
             new DMA { code="644" , country="US" , area="Alexandria, LA" },
             new DMA { code="646" , country="US" , area="Anniston, AL" },
             new DMA { code="647" , country="US" , area="Greenwood-Greenville, MS" },
             new DMA { code="648" , country="US" , area="Champaign & Springfield-Decatur, IL" },
             new DMA { code="649" , country="US" , area="Evansville, IN" },
             new DMA { code="650" , country="US" , area="Oklahoma City, OK" },
             new DMA { code="651" , country="US" , area="Lubbock, TX" },
             new DMA { code="652" , country="US" , area="Omaha, NE" },
             new DMA { code="656" , country="US" , area="Panama City, FL" },
             new DMA { code="657" , country="US" , area="Sherman TX-Ada, OK" },
             new DMA { code="658" , country="US" , area="Green Bay-Appleton, WI" },
             new DMA { code="659" , country="US" , area="Nashville, TN" },
             new DMA { code="661" , country="US" , area="San Angelo, TX" },
             new DMA { code="662" , country="US" , area="Abilene-Sweetwater, TX" },
             new DMA { code="669" , country="US" , area="Madison, WI" },
             new DMA { code="670" , country="US" , area="Ft. Smith-Fayetteville-Springdale-Rogers, AR" },
             new DMA { code="671" , country="US" , area="Tulsa, OK" },
             new DMA { code="673" , country="US" , area="Columbus-Tupelo-West Point, MS" },
             new DMA { code="675" , country="US" , area="Peoria-Bloomington, IL" },
             new DMA { code="676" , country="US" , area="Duluth, MN-Superior, WI" },
             new DMA { code="678" , country="US" , area="Wichita-Hutchinson, KS" },
             new DMA { code="679" , country="US" , area="Des Moines-Ames, IA" },
             new DMA { code="682" , country="US" , area="Davenport, IA-Rock Island-Moline, IL" },
             new DMA { code="686" , country="US" , area="Mobile, AL-Pensacola (Ft. Walton Beach), FL" },
             new DMA { code="687" , country="US" , area="Minot-Bismarck-Dickinson(Williston), ND" },
             new DMA { code="691" , country="US" , area="Huntsville-Decatur (Florence), AL" },
             new DMA { code="692" , country="US" , area="Beaumont-Port Arthur, TX" },
             new DMA { code="693" , country="US" , area="Little Rock-Pine Bluff, AR" },
             new DMA { code="698" , country="US" , area="Montgomery (Selma), AL" },
             new DMA { code="702" , country="US" , area="La Crosse-Eau Claire, WI" },
             new DMA { code="705" , country="US" , area="Wausau-Rhinelander, WI" },
             new DMA { code="709" , country="US" , area="Tyler-Longview(Lufkin & Nacogdoches), TX" },
             new DMA { code="710" , country="US" , area="Hattiesburg-Laurel, MS" },
             new DMA { code="711" , country="US" , area="Meridian, MS" },
             new DMA { code="716" , country="US" , area="Baton Rouge, LA" },
             new DMA { code="717" , country="US" , area="Quincy, IL-Hannibal, MO-Keokuk, IA" },
             new DMA { code="718" , country="US" , area="Jackson, MS" },
             new DMA { code="722" , country="US" , area="Lincoln & Hastings-Kearney, NE" },
             new DMA { code="724" , country="US" , area="Fargo-Valley City, ND" },
             new DMA { code="725" , country="US" , area="Sioux Falls(Mitchell), SD" },
             new DMA { code="734" , country="US" , area="Jonesboro, AR" },
             new DMA { code="736" , country="US" , area="Bowling Green, KY" },
             new DMA { code="737" , country="US" , area="Mankato, MN" },
             new DMA { code="740" , country="US" , area="North Platte, NE" },
             new DMA { code="743" , country="US" , area="Anchorage, AK" },
             new DMA { code="744" , country="US" , area="Honolulu, HI" },
             new DMA { code="745" , country="US" , area="Fairbanks, AK" },
             new DMA { code="746" , country="US" , area="Biloxi-Gulfport, MS" },
             new DMA { code="747" , country="US" , area="Juneau, AK" },
             new DMA { code="749" , country="US" , area="Laredo, TX" },
             new DMA { code="751" , country="US" , area="Denver, CO" },
             new DMA { code="752" , country="US" , area="Colorado Springs-Pueblo, CO" },
             new DMA { code="753" , country="US" , area="Phoenix, AZ" },
             new DMA { code="754" , country="US" , area="Butte-Bozeman, MT" },
             new DMA { code="755" , country="US" , area="Great Falls, MT" },
             new DMA { code="756" , country="US" , area="Billings, MT" },
             new DMA { code="757" , country="US" , area="Boise, ID" },
             new DMA { code="758" , country="US" , area="Idaho Falls-Pocatello, ID" },
             new DMA { code="759" , country="US" , area="Cheyenne, WY-Scottsbluff, NE" },
             new DMA { code="760" , country="US" , area="Twin Falls, ID" },
             new DMA { code="762" , country="US" , area="Missoula, MT" },
             new DMA { code="764" , country="US" , area="Rapid City, SD" },
             new DMA { code="765" , country="US" , area="El Paso, TX" },
             new DMA { code="766" , country="US" , area="Helena, MT" },
             new DMA { code="767" , country="US" , area="Casper-Riverton, WY" },
             new DMA { code="770" , country="US" , area="Salt Lake City, UT" },
             new DMA { code="771" , country="US" , area="Yuma AZ-El Centro, CA" },
             new DMA { code="773" , country="US" , area="Grand Junction-Montrose, CO" },
             new DMA { code="789" , country="US" , area="Tucson (Sierra Vista), AZ" },
             new DMA { code="790" , country="US" , area="Albuquerque-Santa Fe, NM" },
             new DMA { code="798" , country="US" , area="Glendive, MT" },
             new DMA { code="800" , country="US" , area="Bakersfield, CA" },
             new DMA { code="801" , country="US" , area="Eugene, OR" },
             new DMA { code="802" , country="US" , area="Eureka, CA" },
             new DMA { code="803" , country="US" , area="Los Angeles, CA" },
             new DMA { code="804" , country="US" , area="Palm Springs, CA" },
             new DMA { code="807" , country="US" , area="San Francisco-Oakland-San Jose, CA" },
             new DMA { code="810" , country="US" , area="Yakima-Pasco-Richland-Kennewick, WA" },
             new DMA { code="811" , country="US" , area="Reno, NV" },
             new DMA { code="813" , country="US" , area="Medford-Klamath Falls, OR" },
             new DMA { code="819" , country="US" , area="Seattle-Tacoma, WA" },
             new DMA { code="820" , country="US" , area="Portland, OR" },
             new DMA { code="821" , country="US" , area="Bend, OR" },
             new DMA { code="825" , country="US" , area="San Diego, CA" },
             new DMA { code="828" , country="US" , area="Monterey-Salinas, CA" },
             new DMA { code="839" , country="US" , area="Las Vegas, NV" },
             new DMA { code="855" , country="US" , area="Santa Barbara-Santa Maria-San Luis Obispo, CA" },
             new DMA { code="862" , country="US" , area="Sacramento-Stockton-Modesto, CA" },
             new DMA { code="866" , country="US" , area="Fresno-Visalia, CA" },
             new DMA { code="868" , country="US" , area="Chico-Redding, CA" },
             new DMA { code="881" , country="US" , area="Spokane, WA" },
        };

    }
}
